steps:
- name: 'gcr.io/$PROJECT_ID/node8/yarn'
  args: ['install']

- name: 'gcr.io/$PROJECT_ID/node8/yarn'
  args: ['test']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/hello_yarn', '.']

images: ['gcr.io/$PROJECT_ID/hello_yarn']
